name: psnerf
channels:
  - pyg
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python # DONE
  - pytorch=1.8.0 # DONE
  - pytorch-cluster # DONE
  - torchvision  # DONE
  - torchaudio  # DONE
  - cudatoolkit=11.1
  - cffi  # DONE
  - cython  # DONE
  - imageio=2.9.0  # DONE
  - numpy # DONE
  - scipy # DONE
  - matplotlib # DONE
  - pandas # DONE
  - tensorboard # DONE
  - yaml # DONE
  - pillow=8.2.0 # DONE
  - wheel # DONE
  - pip
  - tqdm # DONE
  - pip:
      - ipdb # DONE
      - ipython==7.24.0 # FAIL: https://anaconda.org/anaconda/ipython (seems to have been installed with ipdb)
      - ipython-genutils # DONE
      - jedi # DONE
      - opencv-python # FREEZE in "Solving environment': https://anaconda.org/conda-forge/opencv -> solve: install with pip: pip install opencv-python
      - scikit-image # DONE
      - pyyaml # DONE
      - trimesh # DONE
      - configargparse # DONE
      - imageio-ffmpeg # DONE
      - GPUtil # DONE
      - pyhocon # DONE
      - tensorboardX # DONE
      - plotly # DONE
      - lpips # FREEZE in "Solving environment': https://anaconda.org/conda-forge/lpips -> solve: install with pip: pip install lpips
      - Rtree # DONE
